# Generated by Django 5.2.9 on 2026-03-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
