# Generated by Django 5.2.9 on 2026-03-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_reminder_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="acknowledged",
            field=models.BooleanField(default=False),
        ),
    ]
