# Generated by Django 5.2.9 on 2026-03-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_reminder_acknowledged"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
