# Generated by Django 5.2.9 on 2026-03-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest_house", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guesthouse",
            name="cluster_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="guesthouse",
            name="continent_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="guesthouse",
            name="country_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="guesthouse",
            name="district_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="guesthouse",
            name="mandal_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="guesthouse",
            name="state_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="guesthouse",
            name="visiting_location_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
