# Generated by Django 5.2.9 on 2026-03-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="traveladvance",
            name="hr_remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
