# Generated by Django 4.2.7 on 2026-03-16 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel_masters', '0001_initial'),
        ('travel', '0001_initial'),
        ('core', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='route_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel_masters.routepath'),
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='core.user'),
        ),
        migrations.AddField(
            model_name='travelprovidermaster',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='travelmodemaster',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='travelclaim',
            name='current_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_to_approve', to='core.user'),
        ),
        migrations.AddField(
            model_name='travelclaim',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='travelclaim',
            name='final_executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_processed_claims', to='core.user'),
        ),
        migrations.AddField(
            model_name='travelclaim',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_claims', to='core.user'),
        ),
        migrations.AddField(
            model_name='travelclaim',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_claims', to='core.user'),
        ),
        migrations.AddField(
            model_name='travelclaim',
            name='sent_by_executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_claims', to='core.user'),
        ),
        migrations.AddField(
            model_name='travelclaim',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='travel.trip'),
        ),
        migrations.AddField(
            model_name='traveladvance',
            name='current_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances_to_approve', to='core.user'),
        ),
        migrations.AddField(
            model_name='traveladvance',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='traveladvance',
            name='final_executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_processed_advances', to='core.user'),
        ),
        migrations.AddField(
            model_name='traveladvance',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_advances', to='core.user'),
        ),
        migrations.AddField(
            model_name='traveladvance',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_advances', to='core.user'),
        ),
        migrations.AddField(
            model_name='traveladvance',
            name='sent_by_executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_advances', to='core.user'),
        ),
        migrations.AddField(
            model_name='traveladvance',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='travel.trip'),
        ),
        migrations.AddField(
            model_name='trainprovidermaster',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='trainclassmaster',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='staytypemaster',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='roomtypemaster',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user'),
        ),
        migrations.AddField(
            model_name='mealtypemaster',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='mealcategorymaster',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='mastermodule',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='localtravelmodemaster',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='localprovidermaster',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='localcarsubtypemaster',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='localbikesubtypemaster',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        # migrations.AddField(
        #     model_name='jobreport',
        #     name='deleted_by',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        # ),
        # migrations.AddField(
        #     model_name='jobreport',
        #     name='trip',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_reports', to='travel.trip'),
        # ),
        # migrations.AddField(
        #     model_name='jobreport',
        #     name='user',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_reports', to='core.user'),
        # ),
        migrations.AddField(
            model_name='intercitycabvehiclemaster',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='intercitycabprovidermaster',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='incidentaltypemaster',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='flightclassmaster',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='expense',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='expense',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='travel.trip'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='travel.expense'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='raised_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='core.user'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='travel.trip'),
        ),
        migrations.AddField(
            model_name='custommastervalue',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='travel.custommasterdefinition'),
        ),
        migrations.AddField(
            model_name='custommastervalue',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='custommasterdefinition',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='custommasterdefinition',
            name='module_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='travel.mastermodule'),
        ),
        migrations.AddField(
            model_name='bustypemaster',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='busprovidermaster',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='busoperatormaster',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='bulkactivitybatch',
            name='current_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_to_approve', to='core.user'),
        ),
        migrations.AddField(
            model_name='bulkactivitybatch',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='bulkactivitybatch',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_batches', to='travel.trip'),
        ),
        migrations.AddField(
            model_name='bulkactivitybatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_batches', to='core.user'),
        ),
        migrations.AddField(
            model_name='bookingtypemaster',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='airlinemaster',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddConstraint(
            model_name='custommastervalue',
            constraint=models.UniqueConstraint(fields=('definition', 'name'), name='unique_name_per_definition'),
        ),
    ]
