# Generated by Django 5.2.9 on 2026-03-07 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("travel", "0002_traveladvance_hr_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="traveladvance",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_advances",
                to="core.user",
            ),
        ),
        migrations.AddField(
            model_name="traveladvance",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="travelclaim",
            name="hr_remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="travelclaim",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_claims",
                to="core.user",
            ),
        ),
        migrations.AddField(
            model_name="travelclaim",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_trips",
                to="core.user",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
