# Generated by Django 5.2.9 on 2026-03-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="custommastervalue",
            name="extra_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
