# Generated by Django 5.2.9 on 2026-03-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airlinemaster",
            name="lookup_key",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="bookingtypemaster",
            name="lookup_key",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="busoperatormaster",
            name="lookup_key",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="busprovidermaster",
            name="lookup_key",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="bustypemaster",
            name="lookup_key",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="custommasterdefinition",
            name="key",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="flightclassmaster",
            name="lookup_key",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="incidentaltypemaster",
            name="lookup_key",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="intercitycabprovidermaster",
            name="lookup_key",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="intercitycabvehiclemaster",
            name="lookup_key",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="localbikesubtypemaster",
            name="lookup_key",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="localcarsubtypemaster",
            name="lookup_key",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="localprovidermaster",
            name="lookup_key",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="localtravelmodemaster",
            name="lookup_key",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="mealcategorymaster",
            name="lookup_key",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="mealtypemaster",
            name="lookup_key",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="roomtypemaster",
            name="lookup_key",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="staytypemaster",
            name="lookup_key",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="trainclassmaster",
            name="lookup_key",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="trainprovidermaster",
            name="lookup_key",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="travelmodemaster",
            name="lookup_key",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="travelprovidermaster",
            name="lookup_key",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="cost_estimate",
            field=models.CharField(default="₹0 (Estimated)", max_length=50),
        ),
    ]
