# Generated by Django 5.2.9 on 2026-03-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0003_airlinemaster_lookup_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="trip_id",
            field=models.CharField(
                editable=False,
                max_length=255,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
