# Generated by Django 5.2.9 on 2026-03-27 08:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0003_traveladvance_hod_director_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDailyTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=10, max_digits=20)),
                ("longitude", models.DecimalField(decimal_places=10, max_digits=20)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("speed", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_tracking",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Daily Tracking",
                "verbose_name_plural": "User Daily Tracking Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
