# Generated by Django 5.2.9 on 2026-03-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0003_alter_trip_project_code_alter_trip_trip_id_jobreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="project_code",
            field=models.CharField(blank=True, default="General", max_length=50),
        ),
        migrations.AlterField(
            model_name="trip",
            name="trip_id",
            field=models.CharField(
                editable=False,
                max_length=20,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.DeleteModel(
            name="JobReport",
        ),
    ]
