# Generated by Django 4.2.7 on 2026-03-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_bulkactivitybatch'),
        ('travel', '0003_traveladvance_rejected_by_and_more'),
    ]

    operations = [
    ]
