# Generated by Django 5.2.9 on 2026-03-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0004_userdailytracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="triptracking",
            name="device_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userdailytracking",
            name="device_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
