# Generated by Django 5.2.9 on 2026-03-21 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0004_alter_trip_trip_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalSubTypeMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("sub_type", models.CharField(max_length=100, unique=True)),
                ("is_car", models.BooleanField(default=False)),
                ("is_bike", models.BooleanField(default=False)),
                ("is_auto", models.BooleanField(default=False)),
                (
                    "key",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TravelClassMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("class_name", models.CharField(max_length=100, unique=True)),
                ("is_flight", models.BooleanField(default=False)),
                ("is_train", models.BooleanField(default=False)),
                ("is_bus", models.BooleanField(default=False)),
                (
                    "key",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TravelOperatorMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("operator_name", models.CharField(max_length=100, unique=True)),
                ("is_flight", models.BooleanField(default=False)),
                ("is_train", models.BooleanField(default=False)),
                ("is_bus", models.BooleanField(default=False)),
                (
                    "key",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TravelVehicleMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("vehicle_name", models.CharField(max_length=100, unique=True)),
                ("is_bus", models.BooleanField(default=False)),
                ("is_intercity_cab", models.BooleanField(default=False)),
                (
                    "key",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="busoperatormaster",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="busprovidermaster",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="flightclassmaster",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="intercitycabprovidermaster",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="localbikesubtypemaster",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="localcarsubtypemaster",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="trainclassmaster",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="trainprovidermaster",
            name="deleted_by",
        ),
        migrations.RemoveConstraint(
            model_name="custommastervalue",
            name="unique_code_per_definition",
        ),
        migrations.RemoveField(
            model_name="airlinemaster",
            name="lookup_key",
        ),
        migrations.RemoveField(
            model_name="bookingtypemaster",
            name="lookup_key",
        ),
        migrations.RemoveField(
            model_name="bustypemaster",
            name="lookup_key",
        ),
        migrations.RemoveField(
            model_name="custommasterdefinition",
            name="key",
        ),
        migrations.RemoveField(
            model_name="custommastervalue",
            name="extra_data",
        ),
        migrations.RemoveField(
            model_name="incidentaltypemaster",
            name="lookup_key",
        ),
        migrations.RemoveField(
            model_name="intercitycabvehiclemaster",
            name="lookup_key",
        ),
        migrations.RemoveField(
            model_name="localprovidermaster",
            name="lookup_key",
        ),
        migrations.RemoveField(
            model_name="localtravelmodemaster",
            name="lookup_key",
        ),
        migrations.RemoveField(
            model_name="mealcategorymaster",
            name="lookup_key",
        ),
        migrations.RemoveField(
            model_name="mealtypemaster",
            name="lookup_key",
        ),
        migrations.RemoveField(
            model_name="roomtypemaster",
            name="lookup_key",
        ),
        migrations.RemoveField(
            model_name="staytypemaster",
            name="lookup_key",
        ),
        migrations.RemoveField(
            model_name="travelmodemaster",
            name="lookup_key",
        ),
        migrations.RemoveField(
            model_name="travelprovidermaster",
            name="lookup_key",
        ),
        migrations.AddField(
            model_name="localprovidermaster",
            name="is_auto",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="localprovidermaster",
            name="is_bike",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="localprovidermaster",
            name="is_bus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="localprovidermaster",
            name="is_car",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="localprovidermaster",
            name="is_metro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="localprovidermaster",
            name="key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="travelprovidermaster",
            name="is_bus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="travelprovidermaster",
            name="is_flight",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="travelprovidermaster",
            name="is_intercity_cab",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="travelprovidermaster",
            name="is_train",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="travelprovidermaster",
            name="key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="trip_id",
            field=models.CharField(
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="localsubtypemaster",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="travelclassmaster",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="traveloperatormaster",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="travelvehiclemaster",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="BusOperatorMaster",
        ),
        migrations.DeleteModel(
            name="BusProviderMaster",
        ),
        migrations.DeleteModel(
            name="FlightClassMaster",
        ),
        migrations.DeleteModel(
            name="IntercityCabProviderMaster",
        ),
        migrations.DeleteModel(
            name="LocalBikeSubTypeMaster",
        ),
        migrations.DeleteModel(
            name="LocalCarSubTypeMaster",
        ),
        migrations.DeleteModel(
            name="TrainClassMaster",
        ),
        migrations.DeleteModel(
            name="TrainProviderMaster",
        ),
    ]
