# Generated by Django 4.2.7 on 2026-03-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_custommasterdefinition_remove_travelclaim_hr_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkactivitybatch',
            name='hierarchy_level',
            field=models.IntegerField(default=1),
        ),
    ]
