# Generated by Django 5.2.9 on 2026-03-27 08:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0005_triptracking_device_id_userdailytracking_device_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=10, max_digits=20)),
                ("longitude", models.DecimalField(decimal_places=10, max_digits=20)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("speed", models.FloatField(blank=True, null=True)),
                ("device_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "activity_type",
                    models.CharField(default="Field Activity", max_length=100),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_tracking",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Tracking",
                "verbose_name_plural": "Field Tracking Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
