# Generated by Django 5.2.9 on 2026-03-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_bulkactivitybatch_hierarchy_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_mode',
            field=models.CharField(choices=[('Airways', 'Airways'), ('Train', 'Train'), ('Bus', 'Bus'), ('Car / Jeep / Van', 'Car / Jeep / Van'), ('LCV', 'LCV (Light Commercial Vehicle)'), ('Bus / Truck (2 Axle)', 'Bus / Truck (2 Axle)'), ('3-Axle Commercial', '3-Axle Commercial'), ('MAV (4-6 Axle)', 'MAV (Multi-Axle Vehicle 4-6)'), ('Oversized (7+ Axle)', 'Oversized Vehicle (7+ Axle)'), ('2 Wheeler', '2 Wheeler (Non-Tollable)'), ('3 Wheeler', '3 Wheeler (Non-Tollable)')], default='Airways', max_length=20),
        ),
    ]
