# Generated by Django 4.2.7 on 2026-03-11 06:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_bulkactivitybatch_hierarchy_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_mode',
            field=models.CharField(choices=[('Airways', 'Airways'), ('Train', 'Train'), ('Bus', 'Bus'), ('Car / Jeep / Van', 'Car / Jeep / Van'), ('LCV', 'LCV (Light Commercial Vehicle)'), ('Bus / Truck (2 Axle)', 'Bus / Truck (2 Axle)'), ('3-Axle Commercial', '3-Axle Commercial'), ('MAV (4-6 Axle)', 'MAV (Multi-Axle Vehicle 4-6)'), ('Oversized (7+ Axle)', 'Oversized Vehicle (7+ Axle)'), ('2 Wheeler', '2 Wheeler (Non-Tollable)'), ('3 Wheeler', '3 Wheeler (Non-Tollable)')], default='Airways', max_length=20),
        ),
        migrations.CreateModel(
            name='TripTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='travel.trip')),
            ],
            options={
                'verbose_name': 'Trip Tracking',
                'verbose_name_plural': 'Trip Tracking Points',
                'ordering': ['timestamp'],
            },
        ),
    ]
