# Generated by Django 4.2.7 on 2026-03-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_alter_trip_travel_mode_triptracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='fuel_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
