# Generated by Django 5.2.9 on 2026-03-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0007_alter_trip_travel_mode"),
        ("travel", "0008_trip_fuel_rate_snapshot"),
    ]

    operations = []
