# Generated by Django 5.2.9 on 2026-03-24 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("ERROR", "Error"),
                            ("WARNING", "Warning"),
                            ("INFO", "Info"),
                        ],
                        default="ERROR",
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("FRONTEND", "Frontend"), ("BACKEND", "Backend")],
                        default="BACKEND",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("traceback", models.TextField(blank=True, null=True)),
                ("path", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
