# Generated by Django 5.2.9 on 2026-03-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_management", "0002_systemerrorlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileTrackingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interval_minutes",
                    models.IntegerField(
                        default=15, help_text="Frequency of location updates"
                    ),
                ),
                (
                    "distance_filter",
                    models.IntegerField(
                        default=100,
                        help_text="Minimum distance in meters to trigger update",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Global switch for mobile tracking"
                    ),
                ),
                (
                    "daily_tracking_active",
                    models.BooleanField(
                        default=True,
                        help_text="Enable tracking even when no trip is active",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mobile Tracking Configuration",
                "verbose_name_plural": "Mobile Tracking Configurations",
            },
        ),
    ]
