# Generated by Django 5.2.9 on 2026-03-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_management", "0003_mobiletrackingconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobiletrackingconfig",
            name="latest_version",
            field=models.CharField(
                default="1.0.0",
                help_text="The most recent version of the mobile app",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mobiletrackingconfig",
            name="update_url",
            field=models.URLField(
                blank=True,
                help_text="Direct link to download the latest APK",
                max_length=500,
                null=True,
            ),
        ),
    ]
