# Generated by Django 5.2.9 on 2026-03-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_masters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="routepath",
            name="segment_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Breakdown of distances between points",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="route",
            unique_together={("source", "destination")},
        ),
    ]
