# Generated by Django 5.2.9 on 2026-03-17 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_masters", "0002_routepath_segment_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eligibilityrule",
            options={},
        ),
        migrations.CreateModel(
            name="Jurisdiction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("project_name", models.CharField(max_length=200)),
                ("project_code", models.CharField(max_length=100)),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jurisdictions",
                        to="travel_masters.circle",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "districts",
                    models.ManyToManyField(
                        limit_choices_to={"location_type": "District"},
                        related_name="jurisdiction_districts",
                        to="travel_masters.location",
                    ),
                ),
            ],
            options={
                "ordering": ["project_name", "circle__name"],
                "unique_together": {("project_code", "circle", "is_deleted")},
            },
        ),
    ]
