# Generated by Django 5.2.9 on 2026-03-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel_masters", "0002_routepath_segment_data_alter_route_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="route",
            unique_together=set(),
        ),
    ]
