# Generated by Django 5.2.9 on 2026-03-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_masters", "0003_alter_route_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="tollgate",
            name="registered_id",
            field=models.CharField(
                blank=True, help_text="Manual Registered ID", max_length=50, null=True
            ),
        ),
    ]
