# Generated by Django 4.2.7 on 2026-03-10 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_masters', '0003_alter_route_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routepath',
            name='segment_data',
        ),
    ]
