# Generated by Django 5.2.9 on 2026-03-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_masters", "0004_tollgate_registered_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tollrate",
            name="journey_type",
            field=models.CharField(
                default="UP", help_text="UP, DOWN, or TO_AND_FRO", max_length=20
            ),
        ),
    ]
