# Generated by Django 5.2.9 on 2026-03-11 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_masters', '0004_remove_routepath_segment_data'),
        ('travel_masters', '0005_tollrate_journey_type'),
    ]

    operations = [
    ]
