# Generated by Django 4.2.7 on 2026-03-11 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_attendancefrs_timestamp_and_more'),
        ('travel_masters', '0006_merge_20260311_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelRateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('rate_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user')),
            ],
            options={
                'unique_together': {('state', 'vehicle_type', 'is_deleted')},
            },
        ),
    ]
