# Generated by Django 5.2.9 on 2026-03-11 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_attendancefrs_timestamp_and_more"),
        ("travel_masters", "0007_fuelratemaster"),
    ]

    operations = [
        migrations.CreateModel(
            name="EligibilityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cadre",
                    models.CharField(
                        help_text="e.g. ADMINISTRATIVE, Grade A", max_length=100
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Accommodation, Daily Allowance, Flight, Train, Bus, Local Conveyance, Mileage Rate",
                        max_length=50,
                    ),
                ),
                (
                    "city_type",
                    models.CharField(
                        blank=True,
                        help_text="Metro, Non-Metro, State HQ, Districts, Others, N/A",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "limit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Max eligible amount. 0 if not applicable.",
                        max_digits=10,
                    ),
                ),
                (
                    "eligibility_class",
                    models.CharField(
                        blank=True,
                        help_text="Economy, II A/c, Sleeper, N/A",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "ordering": ["cadre", "category", "city_type"],
                "unique_together": {("cadre", "category", "city_type", "is_deleted")},
            },
        ),
    ]
