# Generated by Django 5.2.9 on 2026-03-11 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_attendancefrs_timestamp_and_more"),
        ("travel_masters", "0008_eligibilityrule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eligibilityrule",
            options={"ordering": ["cadre__name", "category", "city_type"]},
        ),
        migrations.CreateModel(
            name="Cadre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. ADMINISTRATIVE, Grade A",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="eligibilityrule",
            name="cadre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eligibility_rules",
                to="travel_masters.cadre",
            ),
        ),
    ]
