# Generated by Django 5.2.9 on 2026-03-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel_masters", "0006_merge_20260311_1043"),
        ("travel_masters", "0009_alter_eligibilityrule_options_cadre_and_more"),
    ]

    operations = []
