# Generated by Django 5.2.9 on 2026-03-12 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_loginhistory_failure_reason"),
        ("travel_masters", "0010_merge_20260312_1158"),
    ]

    operations = [
        migrations.CreateModel(
            name="Circle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.user",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        limit_choices_to={"location_type": "State"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circles",
                        to="travel_masters.location",
                    ),
                ),
            ],
            options={
                "ordering": ["state__name", "name"],
                "unique_together": {("name", "state", "is_deleted")},
            },
        ),
        migrations.CreateModel(
            name="Jurisdiction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("project_name", models.CharField(max_length=200)),
                ("project_code", models.CharField(max_length=100)),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jurisdictions",
                        to="travel_masters.circle",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.user",
                    ),
                ),
                (
                    "districts",
                    models.ManyToManyField(
                        limit_choices_to={"location_type": "District"},
                        related_name="jurisdiction_districts",
                        to="travel_masters.location",
                    ),
                ),
            ],
            options={
                "ordering": ["project_name", "circle__name"],
                "unique_together": {("project_code", "circle", "is_deleted")},
            },
        ),
    ]
