# Generated by Django 5.2.9 on 2026-03-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel_masters", "0011_circle_jurisdiction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eligibilityrule",
            options={},
        ),
    ]
