# Generated by Django 5.2.9 on 2026-03-09 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allow_photo_reset",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="face_encoding",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="face_photo",
            field=models.ImageField(blank=True, null=True, upload_to="face_photos/"),
        ),
        migrations.AddField(
            model_name="user",
            name="frs_logs_cleared_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_face_enrolled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="AttendanceFRS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo_captured", models.ImageField(upload_to="attendance_captures/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_matched", models.BooleanField(default=False)),
                ("match_score", models.FloatField(default=0.0)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("location_address", models.TextField(blank=True, null=True)),
                ("hierarchy_level", models.IntegerField(default=1)),
                ("status", models.CharField(default="Recorded", max_length=20)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frs_attendance",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="FaceRegistrationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("face_encoding", models.TextField()),
                (
                    "face_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="pending_face_photos/"
                    ),
                ),
                ("status", models.CharField(default="Pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "reporting_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_face_registrations",
                        to="core.user",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_registration_requests",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PhotoUpdateRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("status", models.CharField(default="Pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided_photo_updates",
                        to="core.user",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_update_requests",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
