# Generated by Django 5.2.9 on 2026-03-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="device_id",
            field=models.CharField(
                blank=True,
                help_text="Unique hardware ID of the mobile device",
                max_length=255,
                null=True,
            ),
        ),
    ]
