# Generated by Django 5.2.9 on 2026-03-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_allow_photo_reset_user_face_encoding_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancefrs",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
