# Generated by Django 5.2.9 on 2026-03-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_attendancefrs_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginhistory",
            name="failure_reason",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
