# Generated by Django 5.2.9 on 2026-03-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_loginhistory_failure_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[
                    ("classic", "Classic Burgundy"),
                    ("ocean", "Ocean Blue"),
                    ("teal", "Modern Teal"),
                    ("sunset", "Sunset Orange"),
                    ("midnight", "Midnight Navy"),
                    ("minimal", "Minimalist Gray"),
                ],
                default="classic",
                max_length=50,
            ),
        ),
    ]
