# Generated by Django 5.2.9 on 2026-03-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_user_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[
                    ("classic", "Classic Burgundy"),
                    ("ocean", "Ocean Blue"),
                    ("teal", "Modern Teal"),
                    ("sunset", "Sunset Orange"),
                    ("midnight", "Midnight Navy"),
                    ("minimal", "Minimalist Gray"),
                    ("pastel", "Pastel Dreams"),
                    ("coastal", "Coastal Sand"),
                    ("sunny", "Sunny Sky"),
                    ("slate", "Slate Elegance"),
                    ("tropical", "Tropical Teal"),
                ],
                default="classic",
                max_length=50,
            ),
        ),
    ]
