# Generated by Django 5.2.9 on 2026-03-23 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_user_theme"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSecurityAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_1_hash", models.CharField(max_length=255)),
                ("question_2_hash", models.CharField(max_length=255)),
                ("question_3_hash", models.CharField(max_length=255)),
                ("question_4_hash", models.CharField(max_length=255)),
                ("question_5_hash", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
