# Generated by Django 5.2.9 on 2026-03-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_usersecurityanswer"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRegistrationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=100)),
                ("section", models.CharField(max_length=100)),
                ("project", models.CharField(max_length=100)),
                ("office", models.CharField(max_length=100)),
                ("contact_number", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("HR Approved", "HR Approved"),
                            ("Rejected", "Rejected"),
                            ("Account Created", "Account Created"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("hr_approved_at", models.DateTimeField(blank=True, null=True)),
                ("admin_approved_at", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
